// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGYbUkSqvcPtBCgeTlazxABIQWcBQeSE',
    appId: '1:108053833876:web:77fff1dd84bb1c6613ac81',
    messagingSenderId: '108053833876',
    projectId: 'mobimap-a962b',
    authDomain: 'mobimap-a962b.firebaseapp.com',
    storageBucket: 'mobimap-a962b.appspot.com',
    measurementId: 'G-V1E928YBW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhT0bSnDSK0Uk4rL3spBoakJLugUb6cMA',
    appId: '1:108053833876:android:cb2fcd775f102a1f13ac81',
    messagingSenderId: '108053833876',
    projectId: 'mobimap-a962b',
    storageBucket: 'mobimap-a962b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYGrDXtHTwWq7TTyPt9yyt_z03ppEbog',
    appId: '1:108053833876:ios:65e32da6321c4ce613ac81',
    messagingSenderId: '108053833876',
    projectId: 'mobimap-a962b',
    storageBucket: 'mobimap-a962b.appspot.com',
    iosBundleId: 'com.example.mobimap',
  );
}
